apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore
      version: v3
  template:
    metadata:
      labels:
        app: aspnetcore
        version: v3
    spec:
      containers:
      - name: aspnetcore
        image: weatherweb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # Environment variable section
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
      version: v1
  template:
    metadata:
      labels:
        app: weatherapi
        version: v1
    spec:
      containers:
      - name: weatherapi
        image: weatherapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapi
spec:
  selector:
    app: weatherapi
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-service
  labels:
    app: aspnetcore
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: aspnetcore